# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEuU-sbWCPvCAYznGVhrKxN-eyDPdbbr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()
for filename in uploaded.keys():
    print('Uploaded file:', filename)

df = pd.read_csv("The_World_Bank_Population_growth_(annual_) (1).csv")

df.head()

df.info()

df.describe()

df.sum()

plt.figure(figsize=(10,6))
sns.histplot(df.drop(columns=['country_code','country_name']).values.flatten(),bins=30,kde=True)
plt.title("Distribution of Population Growth Rates")
plt.xlabel('Population Growth (%)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

avg_growth=df.drop(columns=['country_code','country_name']).mean()
plt.figure(figsize=(10,6))
avg_growth.plot(kind='bar',color='blue')
plt.title('Average Population Growth Rate by Year')
plt.xlabel('Year')
plt.ylabel('Average Population Growth (%)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='2021', y='2022', data=df)
plt.title('Scatter Plot: Population Growth Rate (2021) vs. Population Growth Rate (2022)')
plt.xlabel('Population Growth Rate (2021)')
plt.ylabel('Population Growth Rate (2022)')
plt.tight_layout()
plt.show()